# Generated by Django 6.0.5 on 2026-05-28 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.destination'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('best', 'Best Seller'), ('custom', 'Customized'), ('group', 'Group Tour'), ('bike', 'Bike Tour')], max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_reviews',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
