# Generated by Django 6.0.5 on 2026-05-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourdestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdestination',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour-destinations/'),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
