# Generated by Django 6.0.5 on 2026-05-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourdestination_description_tourdestination_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('infants', models.IntegerField(default=0)),
                ('travel_date', models.DateField()),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('total_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='pdf',
            field=models.FileField(default=1, upload_to='package_pdfs/'),
            preserve_default=False,
        ),
    ]
