# Generated by Django 6.0.5 on 2026-06-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_booking_package_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='package',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(default='default.jpg', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
