# Generated by Django 6.0.5 on 2026-06-24 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_cruise_cruisegallery_cruiseinclusion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='itinerary',
        ),
        migrations.CreateModel(
            name='CruiseItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='cruise_itinerary/')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='tours.cruise')),
            ],
        ),
    ]
